---
title: "Analysis Report"
author: "Lavanya Pedamallu"
date: "1/31/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library(readxl)
library(dplyr)
library(data.table)
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
* Determine whether an abnormal SBT and/or AD8 screen is associated with an increase in readmission and/or discharge to a location other than home, length of stay, in-hospital mortality, and early postoperative complications.

* Evaluate the frequency and etiology of early readmission in patients undergoing elective surgery with an abnormal SBT/AD8 

# Inclusion and Exculsion
* **Inclusion criteria**: Patients > 65 years of age undergoing elective surgery who were evaluated in CPAP clinic between January 2013   and June 2018 who underwent one of the following surgical procedures: 

       	Cholecystectomy
       	Colectomy/APR/LAR/SB resection
       	Gastrectomy
  	    Whipple
      	Pancreatectomy
      	Hysterectomy 
      	TAH/BSO
      	Lumbar spine fusion 
      	Total knee arthroplasty
      	Total hip arthroplasty
  	    Total shoulder arthroplasty
      	Laparoscopic hiatal hernia repair
      	Lobectomy (robotic, VATS, or open)
      	Nephrectomy
      	Prostatectomy
      	Cystectomy
  	    Arteriovenous fistula creation


* **Exclusions**: Exclude all patients who do not have complete screening results for both the AD8 and SB. For analysis of discharge to location other than home, exclude patients not residing at home preoperatively. For patients who                  underwent multiple procedures within the study period, only include the first surgical procedure.


# Dataset
  2020_01_15_Gregory_Cognative_Dysfunction_Data
  
# Analysis-1

                      nl                       abnl               Overall
                 (N=19574)                   (N=5896)            (N=25470)
             

Age_at_CPAP			
Mean (SD)	         72.9 (5.90)	        75.6 (6.89)	      73.5 (6.25)
Median [Min, Max]	71.7 [65.0, 101]	74.7 [65.0, 104]	72.4 [65.0, 104]
race			
White	                   15186 (77.6%)	3923 (66.5%)	19109 (75.0%)
Black	                     1010 (5.2%)	592 (10.0%)	1602 (6.3%)
Other	                     1002 (5.1%)	590 (10.0%)	1592 (6.3%)
Missing	                    2376 (12.1%)	791 (13.4%)	3167 (12.4%)
male_sex			
Yes	                    9148 (46.7%)	2960 (50.2%)	12108 (47.5%)
No	                   10425 (53.3%)	2936 (49.8%)	13361 (52.5%)
Missing	1                         (0.0%)	0 (0%)	        1 (0.0%)
bmi_cats			
[14,18.5)	               216 (1.1%)	106 (1.8%)	322 (1.3%)
[18.5,25)	             4362 (22.3%)	1537 (26.1%)	5899 (23.2%)
[25,30)	                    6975 (35.6%)	2023 (34.3%)	8998 (35.3%)
[30,35)                    4677 (23.9%)	        1316 (22.3%)	5993 (23.5%)
[35,40)	                    2142 (10.9%)	563 (9.5%)	2705 (10.6%)
[40,61)                 	1173 (6.0%)	340 (5.8%)	1513 (5.9%)
Missing	                       29 (0.1%)	11 (0.2%)	40 (0.2%)
Coronary artery disease			
Yes	                     4443 (22.7%)	1791 (30.4%)	6234 (24.5%)
No	                   15131 (77.3%)	4105 (69.6%)	19236 (75.5%)
low_barthel			
FALSE	                   14708 (75.1%)	3352 (56.9%)	18060 (70.9%)
TRUE	                    4302 (22.0%)	2341 (39.7%)	6643 (26.1%)
(Missing)	              564 (2.9%)	203 (3.4%)	767 (3.0%)
Congestive heart failure			
Yes	                     1906 (9.7%)	870 (14.8%)	2776 (10.9%)
No	                   17668 (90.3%)	5026 (85.2%)	22694 (89.1%)
Atrial fibrillation or flutter history			
Yes	                    2875 (14.7%)	1067 (18.1%)	3942 (15.5%)
No	                   16699 (85.3%)	4829 (81.9%)	21528 (84.5%)
CVA			
Yes	                    2416 (12.3%)	1293 (21.9%)	3709 (14.6%)
No	                   17158 (87.7%)	4603 (78.1%)	21761 (85.4%)
COPD			
Yes	                    2136 (10.9%)	1028 (17.4%)	3164 (12.4%)
No	                   17438 (89.1%)	4868 (82.6%)	22306 (87.6%)
Asthma			
Yes	                     1883 (9.6%)	565 (9.6%)	2448 (9.6%)
No	                    17691 (90.4%)	5331 (90.4%)	23022 (90.4%)
Peripheral artery disease			
Yes	                      892 (4.6%)	435 (7.4%)	1327 (5.2%)
No	                   18682 (95.4%)	5461 (92.6%)	24143 (94.8%)
Diabetes mellitus			
Yes	                     4916 (25.1%)	1899 (32.2%)	6815 (26.8%)
No	                   14658 (74.9%)	3997 (67.8%)	18655 (73.2%)
Current cancer			
Yes	                    3772 (19.3%)	1153 (19.6%)	4925 (19.3%)
No	                   15802 (80.7%)	4743 (80.4%)	20545 (80.7%)
current_heavy			
FALSE	                    9686 (49.5%)	2452 (41.6%)	12138 (47.7%)
TRUE	                       10 (0.1%)	5 (0.1%)	15 (0.1%)
(Missing)	            9878 (50.5%)	3439 (58.3%)	13317 (52.3%)
prior_heavy_alcohol			
Yes	                      1288 (6.6%)	462 (7.8%)	1750 (6.9%)
No	                    18286 (93.4%)	5434 (92.2%)	23720 (93.1%)
low_functional_capacity			
Yes	                    7961 (40.7%)	3584 (60.8%)	11545 (45.3%)
No	                   11613 (59.3%)	2312 (39.2%)	13925 (54.7%)
cirrhosis			
Yes	                      230 (1.2%)	109 (1.8%)	339 (1.3%)
No	                   19344 (98.8%)	5787 (98.2%)	25131 (98.7%)
dialysis			
Yes	                      281 (1.4%)	195 (3.3%)	476 (1.9%)
No	                   19293 (98.6%)	5701 (96.7%)	24994 (98.1%)



# Analysis-2
The results of the analysis-2 has not readmission patients.
Comparison of COG and ABCOG for Discharge other than home, stroke, TIA, mortality rate. Following are the observations:-
                 conditions Normal_AD8 Abnormal_AD8 Normal_SBT   Abnormal_SBT
1 Discharge_other_than_home      23081         2389      20823          4647
2            Mortality_RATE         50            7         41            16
3                       AKI        235           44         64           215
4                    STroke       3248          629       2831           1046
5                       tia       1134          215       1019          330




# Analysis-3
The results of the analysis-2 had no readmission patients to do analysis-3

# Analysis-4
I calculated the predictive values using Linear Regression model and Generalized Linear Model using the supplement. I took three columns such as SBT, AD8, surgery Procedures to calculate predictive values.

**LRM of AD8 and surgical procedure code**
Residuals:
   Min     1Q Median     3Q    Max 
-1.106 -1.106 -1.106 -0.962 36.470 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  1.10567    0.03960  27.922  < 2e-16 ***
AD8         -0.14403    0.03418  -4.213 2.53e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 5.153 on 19998 degrees of freedom
Multiple R-squared:  0.000887,	Adjusted R-squared:  0.000837 
F-statistic: 17.75 on 1 and 19998 DF,  p-value: 2.526e-05

aauracy_test: 0.04478976

**LRM of SBT and surgical procedure code**
Residuals:
   Min     1Q Median     3Q    Max 
-1.139 -1.139 -1.063 -0.987 36.316 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  1.13944    0.04522  25.198  < 2e-16 ***
SBT         -0.03799    0.01027  -3.701 0.000216 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 5.154 on 19998 degrees of freedom
Multiple R-squared:  0.0006844,	Adjusted R-squared:  0.0006344 
F-statistic:  13.7 on 1 and 19998 DF,  p-value: 0.0002155

accuracy test: 0.5590494

**LRM of AD8 and SBT**
Residuals:
    Min      1Q  Median      3Q     Max 
-3.5930 -0.3783 -0.1311 -0.1311  7.8689 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 0.131060   0.008524   15.38   <2e-16 ***
SBT         0.123640   0.001935   63.90   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.9714 on 19998 degrees of freedom
Multiple R-squared:  0.1695,	Adjusted R-squared:  0.1695 
F-statistic:  4083 on 1 and 19998 DF,  p-value: < 2.2e-16
accuracy test: 0.2491773

**GLMof AD8 and SBT**
Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.7516  -0.3522  -0.3522  -0.3522   2.3711  

Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept) -2.74905    0.03285  -83.69   <2e-16 ***
SBT_cat      1.62924    0.05074   32.11   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 12436  on 19999  degrees of freedom
Residual deviance: 11478  on 19998  degrees of freedom
AIC: 11482

Number of Fisher Scoring iterations: 5

Accuracy test: 0.09433272

**GLM of AD8 and surgical procedure code**
Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.078  -1.078  -1.078  -1.078  36.324  

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  1.07795    0.03828   28.16  < 2e-16 ***
AD8_cat     -0.40150    0.12509   -3.21  0.00133 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for gaussian family taken to be 26.5635)

    Null deviance: 531490  on 19999  degrees of freedom
Residual deviance: 531217  on 19998  degrees of freedom
AIC: 122352

Number of Fisher Scoring iterations: 2
accuracy test: 0.04478976

**GLM of SBT and surgical procedure code**
Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.087  -1.087  -1.087  -1.087  36.173  

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  1.08716    0.04025  27.007  < 2e-16 ***
SBT_cat     -0.25970    0.09482  -2.739  0.00617 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for gaussian family taken to be 26.56721)

    Null deviance: 531490  on 19999  degrees of freedom
Residual deviance: 531291  on 19998  degrees of freedom
AIC: 122355

Number of Fisher Scoring iterations: 2
Accuracy test:0.1904936

**AD8 and SBT table**

tab1
    
       0    1    2    3    4    5    6    7    8<-AD8
  0  9780 1143  261   91   41   19    9    0    4
  2  4344  984  252  102   39   25   10    6    3
  3    85   12   10    3    3    2    0    0    1
  4  2545  681  212   84   47   18    5    2    0
  5    61   16   11    2    4    0    0    1    2
  6  1113  490  126   56   29   22   12    3    4
  7    57   18   11    8    4    5    2    1    2
  8   583  252   77   57   40   14   11    6    0
  9    42   14    7    8    3    4    0    0    1
  10  272  140   51   30   26   18   10    5    4
  11   19    8    7    6    3    5    3    4    0
  12  129   68   38   31   24   13    7    2    5
  13   19    7    5    6    2    4    5    4    0
  14   68   26   21   15    9   14    9    4    2
  15   10    2    8    5    5    5    3    1    2
  16   29   12    5    4   10    5    2    2    2
  17   10    2    5    4    2   10    4    3    5
  18    9    5    5    2    5    5    4    2    1
  19    5    2    1    3    2    3    1    3    2
  20    0    1    1    1    1    0    2    4    2
  21    4    0    4    1    3    5    0    2    2
  22    3    1    3    2    1    1    0    0    2
  23    1    1    0    2    0    2    0    0    0
  24    0    1    0    0    1    2    0    3    2
  25    1    1    0    2    2    2    4    4    2
  26    0    0    0    0    1    1    0    1    1
  28    3    2    1    2    0    1    2    2    7
# 